### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Emafire003** [EslaMx7/ScreenTask#38]
Hi, i was going to try this out in order to stream my desktop to my phone, but when I downloaded the new version my antivirus detected it as a trojan malware (Trojan:Win32/Wacatac.D7!ml). So I wanted to know why it does that and let you know in order to fix it. 

Also, side question, i tried the first version before, and i was curios to know how i could increase the FPS rate, or the rate at which it capture the screen from 100ms to at least 20ms or maybe 10ms in order to have a smoother experience.

Thank you in advance!

**Comment by EslaMx7** [comment]
Hi @Emafire003 

Thank you for your feedback, I really appreciate it.

I have scanned the extracted binary on VirusTotal:
https://www.virustotal.com/gui/file/83ed1815529141e7d86ffcbc3ebe6b1a7f0d8c5f63e453d957970961f0c58295/detection
and it's clear!

Can you please provide your `VirusTotal` results, or more info about your AntiVirus so I can check it myself?
It could be a false positive warning, because I'm using the `WinRAR` Self Extract feature to setup the app icons on the Desktop, etc.. I think I will retire this way in the next release to be truly portable executable.


for your FPS question, currently, the minimum is 100ms (to prevent CPU overkill), I think I should remove this limit in the next version and just give the user a `HINT` about the consequences.

**Comment by Emafire003** [comment]
https://www.virustotal.com/gui/file/7ccf8ba313bdd7995f7b755972c226b038227dd25556388c6cb828ae0b2a7836/detection
It detects it as a malware even here.

My anitvirus is simply Windows Defender so idk.

**Comment by MaxiKittyw** [comment]
@Emafire003 I've looked around and doubled checked and there does not appear to be anything malicious in the code. It's strange that virus total is saying that it detects it, make sure you have the latest version downloaded. My windows defender doesn't pick up anything when I scanned the file with it.
I've rebuilt the exe from the repos and here are the results from my end. https://www.virustotal.com/gui/file/7e828c5211ccd8db2effc7dcca1b025c000b63f255c77e49d83010d9acfcfa50/detection

**Comment by Emafire003** [comment]
Uhm i just downloaded the exe, i didn't build it from scratch yet, and it still detects it as a malware. That's weird. (downloaded using https://github.com/EslaMx7/ScreenTask/releases/download/v1.1/ScreenTask.v1.1.exe). (I'm not saying this program is a malware, just letting know that it can be detected as one)

**Comment by MaxiKittyw** [comment]
@Emafire003 Ahhh I see, that's very strange. Unless it's using a different source than the one uploaded to github I wouldn't honestly know. Very strange indeed.

**Comment by EslaMx7** [comment]
@Emafire003 @MaxiKittyw that's very strange for me too, I will do another release this weekend this should change the executable file signature for `VirusTotal`, I hope we can get clean results for everyone.

**Comment by starlyth** [comment]
I hope I'm helping, as this is only the second time I've actually tried something like this. I tried to build the Git in Visual Studio 2019. The issue seems to be frmMain.resx

It states: "Couldn't process file frmMain.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files."

**Comment by MaxiKittyw** [comment]
@starlyth That error simply caused because you downloaded the files from the internet zone. Normally caused when you download files from the internet, either separately or inside a .zip file or similar. You should just be able to right-click it from windows explorer and there should be an option that says unblock. That's normally an issue on your end because of the way you downloaded the files, if you continue to run into this error let me know.
Thanks you for trying to help and contribute.

**Comment by starlyth** [comment]
Yeah. I figured that out. I should have looked up the error before posting. Once I set the zip as unblocked, decompressed that file, and complied from there, there were no issues. I was able to successfully compile and run ScreenTask after that was done.

**Comment by HamzaFouad** [comment]
my windows defender also detected `Trojan:Win32/Woreflint.A!cl`

**Comment by aschoppy** [comment]
It is the same with my file I just downloaded and send to virustotal and also Trojan.Win32.Save.a , W32/Trojan.SIDZ-2188  was detected. May you have an idea ?

**Comment by ElBedeawi** [comment]
Virus Total check for the latest release [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2) seems to be fine now

https://www.virustotal.com/gui/url/2c505b4572016accd7436c2d1082bfc8cfb1e5bb321f1d16cc5359cdcda88569?nocache=1
![image](https://user-images.githubusercontent.com/1478503/155140860-559e1147-e115-442b-bdf4-5e77013790cd.png)
